### ISSUE TITLE
Release 0.6 planned changes

### ISSUE THREAD

**Issue by Drizzt1991** [benjamin-hodgson/asynqp#73]
Will try to summarise the changes, that are planned (At least I want to do) for 0.6:
* [ ] Rewrite the test suite into py.test.
* [ ] Add support for Python3.5 async syntax. Mostly it will cover #34 proposals.
* [ ] Finish the conformance for basic, exchange and queue sections. Mostly those require to implement simple methods and add arguments, no internals should be fixed. See [docs](http://asynqp.readthedocs.org/en/latest/conformance.html). Will fix #68 also
* [ ] Add publish confirms. This will cover issue #62, at least on confirm channels. This will also cover #56, as we can wait for flush by waiting for publish ACK.
* [ ] Add 2 helper's AMQPPublisher and AMQPConsumer, that will implement simple usecase's with reconnect behaviour. We can refer to this as HighLevel API.

@benjamin-hodgson any objections, suggestions?

**Comment by benjamin-hodgson** [comment]
All of these sound like good proposals for v0.6 😄 . We should probably start a longer-term discussion about getting to v1, too.

**Comment by Drizzt1991** [comment]
Hi, I think v1 will come out after we cover all the spec for AMQP and have it run for at least a few month. Something like that. Or did you have any different ideas for the long-term discussion?

By the way, where's v0.5? Do we still have something missing for it?

**Comment by fireflystorm** [comment]
@tvoinarovskyi I see that the release version has been bumped to 0.6 but are the above implemented?
What's new in 0.6?
